set_property(GLOBAL PROPERTY ENGINE_INCLUDE_PATHS)
set_property(GLOBAL PROPERTY ENGINE_SOURCE_FILES)

function(target_include_engine_directory include_path)
    get_property(TEMP GLOBAL PROPERTY ENGINE_INCLUDE_PATHS)
    list(APPEND TEMP "${CMAKE_CURRENT_SOURCE_DIR}/${include_path}")
    set_property(GLOBAL PROPERTY ENGINE_INCLUDE_PATHS ${TEMP})
    # message(WARNING ${TEMP})
endfunction()

function(target_add_engine_sources)
    get_property(TEMP GLOBAL PROPERTY ENGINE_SOURCE_FILES)
    foreach(file ${ARGV})
        list(APPEND TEMP ${CMAKE_CURRENT_SOURCE_DIR}/${file})
    endforeach()
    set_property(GLOBAL PROPERTY ENGINE_SOURCE_FILES ${TEMP})
endfunction()